### ISSUE TITLE
v5.0.0 is throwing (intermediate value).resolve is not a function error

### ISSUE THREAD

**Issue by amamenko** [ChappIO/gatsby-remark-mermaid#22]
Since upgrading `gatsby-remark-mermaid` to v5.0.0 I am seeing the following error on all page queries:

```
ERROR #85901  GRAPHQL.UNKNOWN

There was an error in your GraphQL query:

(intermediate value).resolve is not a function

   1 | query page($name: String!) {
   2 |   file: file(
   3 |     name: {eq: $name}
   4 |   ) {
   5 |     childMarkdownRemark {
>  6 |       html
     |       ^

...

  TypeError: (intermediate value).resolve is not a function
  
  - mermaid-isomorphic.ts:6 
    [docs]/[mermaid-isomorphic]/src/mermaid-isomorphic.ts:6:26
  
  - module_job:194 ModuleJob.run
    node:internal/modules/esm/module_job:194:25
```

downgrading to v4 fixes the error so this is a newly-introduced bug.

**Comment by remcohaszing** [comment]
Duplicate of https://github.com/remcohaszing/mermaid-isomorphic/issues/9
